#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -e /run/tunproxy/state ] && command -v tunproxy >/dev/null 2>&1; then
            tunproxy off
        fi
        ;;
esac

#DEBHELPER#

exit 0
