#!/bin/sh
# Regenerate include/tunproxy/core_manifest.hpp for a sing-box release.
#
# Usage: tools/update-core-manifest.sh <sing-box-version>
#
# Downloads the official linux-amd64 archive over HTTPS, records sizes and
# SHA-256 digests for the archive, executable, and LICENSE, and reads the
# revision from the executable. Review the diff and update the documentation
# files listed at the end before committing.
set -eu

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <sing-box-version>" >&2
    exit 2
fi

VERSION=$1
case "$VERSION" in
    *[!0-9.]*|"") echo "error: version must look like 1.13.18" >&2; exit 2 ;;
esac

ROOT=$(cd "$(dirname "$0")/.." && pwd)
HEADER="$ROOT/include/tunproxy/core_manifest.hpp"
DIRECTORY="sing-box-${VERSION}-linux-amd64"
ASSET="${DIRECTORY}.tar.gz"
URL="https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/${ASSET}"

OLD_VERSION=$(sed -n 's/^    "\([0-9][0-9.]*\)",$/\1/p' "$HEADER" | head -n 1)

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo "Downloading $URL"
curl --fail --location --proto =https --tlsv1.2 --connect-timeout 15 --max-time 600 \
    --output "$WORK/$ASSET" "$URL"

ARCHIVE_SIZE=$(stat -c %s "$WORK/$ASSET")
ARCHIVE_SHA256=$(sha256sum "$WORK/$ASSET" | cut -c1-64)

tar --extract --gzip --file "$WORK/$ASSET" --directory "$WORK" \
    --no-same-owner --no-same-permissions -- "$DIRECTORY/sing-box" "$DIRECTORY/LICENSE"
chmod 0755 "$WORK/$DIRECTORY/sing-box"

BINARY_SIZE=$(stat -c %s "$WORK/$DIRECTORY/sing-box")
BINARY_SHA256=$(sha256sum "$WORK/$DIRECTORY/sing-box" | cut -c1-64)
LICENSE_SHA256=$(sha256sum "$WORK/$DIRECTORY/LICENSE" | cut -c1-64)

VERSION_OUTPUT=$("$WORK/$DIRECTORY/sing-box" version)
printf '%s\n' "$VERSION_OUTPUT" | grep -qx "sing-box version $VERSION" || {
    echo "error: executable does not report version $VERSION" >&2
    printf '%s\n' "$VERSION_OUTPUT" >&2
    exit 1
}
REVISION=$(printf '%s\n' "$VERSION_OUTPUT" | sed -n 's/^Revision: \([0-9a-f]*\)$/\1/p' | head -n 1)
if [ -z "$REVISION" ]; then
    echo "error: cannot read revision from version output" >&2
    exit 1
fi

for digest in "$ARCHIVE_SHA256" "$BINARY_SHA256" "$LICENSE_SHA256"; do
    case "$digest" in
        [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]*) [ "${#digest}" -eq 64 ] ;;
        *) false ;;
    esac || { echo "error: invalid SHA-256 digest computed" >&2; exit 1; }
done

cat > "$HEADER" <<HPP
#pragma once

#include <cstdint>
#include <string_view>

namespace tunproxy {

struct CoreReleaseManifest {
    std::string_view version;
    std::string_view revision;
    std::string_view asset_name;
    std::string_view download_url;
    std::uintmax_t archive_size;
    std::string_view archive_sha256;
    std::string_view binary_member;
    std::uintmax_t binary_size;
    std::string_view binary_sha256;
    std::string_view license_member;
    std::string_view license_sha256;
};

// Generated by tools/update-core-manifest.sh. Every value below is verified at
// download time; changing one without the others makes the core unusable.
inline constexpr CoreReleaseManifest kSingBoxRelease{
    "${VERSION}",
    "${REVISION}",
    "${ASSET}",
    "https://github.com/SagerNet/sing-box/releases/download/v${VERSION}/"
    "${ASSET}",
    ${ARCHIVE_SIZE},
    "${ARCHIVE_SHA256}",
    "${DIRECTORY}/sing-box",
    ${BINARY_SIZE},
    "${BINARY_SHA256}",
    "${DIRECTORY}/LICENSE",
    "${LICENSE_SHA256}",
};

} // namespace tunproxy
HPP

echo "Updated $HEADER"
echo "  version   $VERSION"
echo "  revision  $REVISION"
echo "  archive   $ARCHIVE_SIZE bytes  $ARCHIVE_SHA256"
echo "  sing-box  $BINARY_SIZE bytes  $BINARY_SHA256"
echo "  LICENSE   $LICENSE_SHA256"

if [ -n "$OLD_VERSION" ] && [ "$OLD_VERSION" != "$VERSION" ]; then
    echo
    echo "Files still mentioning $OLD_VERSION:"
    grep -rln --exclude-dir=.git -- "$OLD_VERSION" "$ROOT/README.md" "$ROOT/THIRD_PARTY_NOTICES.md" \
        "$ROOT/docs" "$ROOT/debian" 2>/dev/null | sed 's/^/  /' || true
fi
